/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getBrandMission' : IDL.Func([], [IDL.Text], ['query']),
  'getCartContents' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, CartItem))],
      ['query'],
    ),
  'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getContactForms' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, ContactForm))],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
      ['query'],
    ),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateBrandMission' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getBrandMission' : IDL.Func([], [IDL.Text], ['query']),
    'getCartContents' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, CartItem))],
        ['query'],
      ),
    'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getContactForms' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, ContactForm))],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Product))],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateBrandMission' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };