/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface ContactForm {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Product {
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'price' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<[string, bigint, string, string], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], undefined>,
  'getBrandMission' : ActorMethod<[], string>,
  'getCartContents' : ActorMethod<[], Array<[bigint, CartItem]>>,
  'getCartTotal' : ActorMethod<[], bigint>,
  'getContactForms' : ActorMethod<[], Array<[bigint, ContactForm]>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[], Array<[bigint, Product]>>,
  'removeFromCart' : ActorMethod<[bigint], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'updateBrandMission' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];